//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp25
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public int id { get; set; }
        public Nullable<int> house_id { get; set; }
        public Nullable<int> part_id { get; set; }
        public Nullable<int> sector_id { get; set; }
        public Nullable<int> undersector_id { get; set; }
        public string breaking { get; set; }
        public string repairs { get; set; }
        public System.DateTime date_begine { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public Nullable<double> cost { get; set; }
    
        public virtual Houses Houses { get; set; }
        public virtual Parts Parts { get; set; }
        public virtual Sectors Sectors { get; set; }
        public virtual Undersectors Undersectors { get; set; }
    }
}
