//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp25
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DefectationEntities : DbContext
    {
        public DefectationEntities()
            : base("name=DefectationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Houses> Houses { get; set; }
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<Parts> Parts { get; set; }
        public virtual DbSet<Sectors> Sectors { get; set; }
        public virtual DbSet<Undersectors> Undersectors { get; set; }
    }
}
